// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.21.2
// source: some.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HandlerOneRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	System string `protobuf:"bytes,1,opt,name=system,proto3" json:"system,omitempty"`
}

func (x *HandlerOneRequest) Reset() {
	*x = HandlerOneRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_some_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HandlerOneRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandlerOneRequest) ProtoMessage() {}

func (x *HandlerOneRequest) ProtoReflect() protoreflect.Message {
	mi := &file_some_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandlerOneRequest.ProtoReflect.Descriptor instead.
func (*HandlerOneRequest) Descriptor() ([]byte, []int) {
	return file_some_proto_rawDescGZIP(), []int{0}
}

func (x *HandlerOneRequest) GetSystem() string {
	if x != nil {
		return x.System
	}
	return ""
}

type HandlerOneResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	System   string `protobuf:"bytes,1,opt,name=system,proto3" json:"system,omitempty"`
	Os       string `protobuf:"bytes,2,opt,name=os,proto3" json:"os,omitempty"`
	Hardware string `protobuf:"bytes,3,opt,name=hardware,proto3" json:"hardware,omitempty"`
}

func (x *HandlerOneResponse) Reset() {
	*x = HandlerOneResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_some_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HandlerOneResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandlerOneResponse) ProtoMessage() {}

func (x *HandlerOneResponse) ProtoReflect() protoreflect.Message {
	mi := &file_some_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandlerOneResponse.ProtoReflect.Descriptor instead.
func (*HandlerOneResponse) Descriptor() ([]byte, []int) {
	return file_some_proto_rawDescGZIP(), []int{1}
}

func (x *HandlerOneResponse) GetSystem() string {
	if x != nil {
		return x.System
	}
	return ""
}

func (x *HandlerOneResponse) GetOs() string {
	if x != nil {
		return x.Os
	}
	return ""
}

func (x *HandlerOneResponse) GetHardware() string {
	if x != nil {
		return x.Hardware
	}
	return ""
}

type HandlerTwoRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code       string `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Id         int64  `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	IsReviewed bool   `protobuf:"varint,3,opt,name=is_reviewed,json=isReviewed,proto3" json:"is_reviewed,omitempty"`
}

func (x *HandlerTwoRequest) Reset() {
	*x = HandlerTwoRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_some_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HandlerTwoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandlerTwoRequest) ProtoMessage() {}

func (x *HandlerTwoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_some_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandlerTwoRequest.ProtoReflect.Descriptor instead.
func (*HandlerTwoRequest) Descriptor() ([]byte, []int) {
	return file_some_proto_rawDescGZIP(), []int{2}
}

func (x *HandlerTwoRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *HandlerTwoRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *HandlerTwoRequest) GetIsReviewed() bool {
	if x != nil {
		return x.IsReviewed
	}
	return false
}

type HandlerTwoResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code  int32  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Error string `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *HandlerTwoResponse) Reset() {
	*x = HandlerTwoResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_some_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HandlerTwoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandlerTwoResponse) ProtoMessage() {}

func (x *HandlerTwoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_some_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandlerTwoResponse.ProtoReflect.Descriptor instead.
func (*HandlerTwoResponse) Descriptor() ([]byte, []int) {
	return file_some_proto_rawDescGZIP(), []int{3}
}

func (x *HandlerTwoResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *HandlerTwoResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_some_proto protoreflect.FileDescriptor

var file_some_proto_rawDesc = []byte{
	0x0a, 0x0a, 0x73, 0x6f, 0x6d, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x53, 0x6f,
	0x6d, 0x65, 0x2e, 0x56, 0x31, 0x1a, 0x1c, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x61, 0x70,
	0x69, 0x2f, 0x61, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x22, 0x2b, 0x0a, 0x11, 0x48, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x72, 0x4f, 0x6e,
	0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x79, 0x73, 0x74,
	0x65, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x79, 0x73, 0x74, 0x65, 0x6d,
	0x22, 0x58, 0x0a, 0x12, 0x48, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x72, 0x4f, 0x6e, 0x65, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x79, 0x73, 0x74, 0x65, 0x6d,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x12, 0x0e,
	0x0a, 0x02, 0x6f, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x6f, 0x73, 0x12, 0x1a,
	0x0a, 0x08, 0x68, 0x61, 0x72, 0x64, 0x77, 0x61, 0x72, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x68, 0x61, 0x72, 0x64, 0x77, 0x61, 0x72, 0x65, 0x22, 0x58, 0x0a, 0x11, 0x48, 0x61,
	0x6e, 0x64, 0x6c, 0x65, 0x72, 0x54, 0x77, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x63,
	0x6f, 0x64, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x02, 0x69, 0x64, 0x12, 0x1f, 0x0a, 0x0b, 0x69, 0x73, 0x5f, 0x72, 0x65, 0x76, 0x69, 0x65, 0x77,
	0x65, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0a, 0x69, 0x73, 0x52, 0x65, 0x76, 0x69,
	0x65, 0x77, 0x65, 0x64, 0x22, 0x3e, 0x0a, 0x12, 0x48, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x72, 0x54,
	0x77, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f,
	0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x14,
	0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65,
	0x72, 0x72, 0x6f, 0x72, 0x32, 0xd8, 0x01, 0x0a, 0x04, 0x53, 0x6f, 0x6d, 0x65, 0x12, 0x65, 0x0a,
	0x0a, 0x48, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x72, 0x4f, 0x6e, 0x65, 0x12, 0x1a, 0x2e, 0x53, 0x6f,
	0x6d, 0x65, 0x2e, 0x56, 0x31, 0x2e, 0x48, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x72, 0x4f, 0x6e, 0x65,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1b, 0x2e, 0x53, 0x6f, 0x6d, 0x65, 0x2e, 0x56,
	0x31, 0x2e, 0x48, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x72, 0x4f, 0x6e, 0x65, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x1e, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x18, 0x12, 0x16, 0x2f, 0x76,
	0x31, 0x2f, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x2f, 0x68, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x72,
	0x5f, 0x6f, 0x6e, 0x65, 0x12, 0x69, 0x0a, 0x0a, 0x48, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x72, 0x54,
	0x77, 0x6f, 0x12, 0x1a, 0x2e, 0x53, 0x6f, 0x6d, 0x65, 0x2e, 0x56, 0x31, 0x2e, 0x48, 0x61, 0x6e,
	0x64, 0x6c, 0x65, 0x72, 0x54, 0x77, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1b,
	0x2e, 0x53, 0x6f, 0x6d, 0x65, 0x2e, 0x56, 0x31, 0x2e, 0x48, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x72,
	0x54, 0x77, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x22, 0x82, 0xd3, 0xe4,
	0x93, 0x02, 0x1c, 0x22, 0x17, 0x2f, 0x76, 0x31, 0x2f, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65,
	0x2f, 0x68, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x72, 0x5f, 0x74, 0x77, 0x6f, 0x3a, 0x01, 0x2a, 0x42,
	0x24, 0x5a, 0x22, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x7a, 0x69,
	0x6b, 0x77, 0x61, 0x6c, 0x6c, 0x2f, 0x73, 0x6f, 0x6d, 0x65, 0x2f, 0x61, 0x6e, 0x6f, 0x74, 0x68,
	0x65, 0x72, 0x2f, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_some_proto_rawDescOnce sync.Once
	file_some_proto_rawDescData = file_some_proto_rawDesc
)

func file_some_proto_rawDescGZIP() []byte {
	file_some_proto_rawDescOnce.Do(func() {
		file_some_proto_rawDescData = protoimpl.X.CompressGZIP(file_some_proto_rawDescData)
	})
	return file_some_proto_rawDescData
}

var file_some_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_some_proto_goTypes = []interface{}{
	(*HandlerOneRequest)(nil),  // 0: Some.V1.HandlerOneRequest
	(*HandlerOneResponse)(nil), // 1: Some.V1.HandlerOneResponse
	(*HandlerTwoRequest)(nil),  // 2: Some.V1.HandlerTwoRequest
	(*HandlerTwoResponse)(nil), // 3: Some.V1.HandlerTwoResponse
}
var file_some_proto_depIdxs = []int32{
	0, // 0: Some.V1.Some.HandlerOne:input_type -> Some.V1.HandlerOneRequest
	2, // 1: Some.V1.Some.HandlerTwo:input_type -> Some.V1.HandlerTwoRequest
	1, // 2: Some.V1.Some.HandlerOne:output_type -> Some.V1.HandlerOneResponse
	3, // 3: Some.V1.Some.HandlerTwo:output_type -> Some.V1.HandlerTwoResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_some_proto_init() }
func file_some_proto_init() {
	if File_some_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_some_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HandlerOneRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_some_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HandlerOneResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_some_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HandlerTwoRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_some_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HandlerTwoResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_some_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_some_proto_goTypes,
		DependencyIndexes: file_some_proto_depIdxs,
		MessageInfos:      file_some_proto_msgTypes,
	}.Build()
	File_some_proto = out.File
	file_some_proto_rawDesc = nil
	file_some_proto_goTypes = nil
	file_some_proto_depIdxs = nil
}
